---
title: "SCTLD_juvies"
output: html_document
date: "2024-04-15"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Data analysis for the 16S SCTLD juvenile experiment

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(plyr) 
library(dplyr)
library(ggplot2)
library(ggpubr)
library(lmerTest)
library(car)
library(emmeans)
library(gridExtra)
library(multcomp)
library(reshape)
library(factoextra)
library(reshape2)
library(vegan) 
library(pairwiseAdonis)
library("scales")
packageVersion("scales")
library(RColorBrewer)
library(colorRamps)
library(devtools)
library(phyloseq)
library(readr)
library(vegan)
library(ape)
library(geosphere)
library(ade4)
library(microbiome)  
library(knitr)
```

#Start analysis here: load in RData if needed
```{r}
load("RData/Bac.seqFLU.RData") #load cleaned data 
sample_sums_vector <- sample_sums(Bac.seq.F.2)

Bac.seqFLU <- names(sample_sums_vector[sample_sums_vector >= 1500])
Bac.seqFLU.15k <- prune_samples(Bac.seqFLU, Bac.seq.F.2)
#check if it worked
 nsamples(Bac.seq.F.2)
 nsamples(Bac.seqFLU.15k)
```

#Set up, Bac.s relative abundaces: Bac.seq.rel (Bac.seq for alpha)
```{r}        
#make relative abundance df Bac.seq
Bac.seq.rel  = transform_sample_counts(Bac.seqFLU.15k, function(x) x / sum(x) )  #save as RELA DIVs
data.Bac.seq.rel.sd <- as(sample_data(Bac.seq.rel), "data.frame") #look at samp data
data.Bac.seq.rel = prune_taxa(taxa_sums(Bac.seq.rel) > 0, Bac.seq.rel) #this removes any OTU with 0s

#heatmap
  #plot_heatmap(Bac.s.rel, method = "NMDS", distance = "bray")# way too much data

``` 

unneed
```{r}
# data.Bac.seq.rel df
Bac.seq.S.rel<-subset_samples (data.Bac.seq.rel, experiment=="SCTLD")
Bac.seq.S.rel2<-subset_samples(Bac.seq.S.rel, time.point!= "bath")
Bac.seq.S.rel2<-subset_samples(Bac.seq.S.rel2, experiment!= "NTC")
Bac.seq.S.rel2<-subset_samples(Bac.seq.S.rel2, experiment!= "MOCK")
Bac.seq.S.rel2<-subset_samples(Bac.seq.S.rel2, experiment!= "FLU")
Bac.seq.S.rel2<-subset_samples(Bac.seq.S.rel2, species!= "Orbicella faveolata")
Bac.seq.S.rel2<-subset_samples(Bac.seq.S.rel2, species!= "Montastrea cavernosa")
Bac.seq.S.rel2 = prune_taxa(taxa_sums(Bac.seq.S.rel2) > 0, Bac.seq.S.rel2) #this removes any OTU with 0s

Bac.seq.S.rel2.sd <- as(sample_data(Bac.seq.S.rel2), "data.frame") #look at samp data

```

Unifrac data.Bac.seq.rel
```{r}
#make unifrac matrix
Bac.seq.wu.all <- phyloseq::distance(data.Bac.seq.rel, method = "wunifrac")
s.u.samp.df <- as(sample_data(data.Bac.seq.rel), "data.frame") #sample df

#adonixs test between sample types: not sig. we dont have enough of other species
set.seed(30)
adonis2(Bac.seq.wu.all ~ species, data = s.u.samp.df)
adonis2(Bac.seq.wu.all ~ treatment, data = s.u.samp.df)
adonis2(Bac.seq.wu.all ~ species*treatment, data = s.u.samp.df)

# Pairwise comparisons using pairwise.adonis2
pairwise_results <- pairwise.adonis2(Bac.seq.wu.all ~ species, data = s.u.samp.df)
print(pairwise_results)

#Plot

#nmds
unifrac.all <- ordinate(data.Bac.seq.rel, method="NMDS", "unifrac",weighted=TRUE, set.seed(30)) 
stressplot(unifrac.all)
scores.ord.u_RelA_stats<-as.data.frame(cbind(vegan::scores(unifrac.all, display="sites")))  
     unifrac.all.sd <- as(sample_data(data.Bac.seq.rel), "data.frame") #sample df

scores.ord.u_RelA_stats$species <- unifrac.all.sd$species
scores.ord.u_RelA_stats$treatment <- unifrac.all.sd$treatment
scores.ord.u_RelA_stats$time.point <- unifrac.all.sd$time.point


#plot 
p<-ggplot(scores.ord.u_RelA_stats, aes(x = NMDS1, y = NMDS2)) + 
  geom_point(aes(colour = species, shape=treatment), size = 4) +
 # scale_color_manual(values = c("gray", "darkblue", "red")) +
  stat_ellipse(aes(x = NMDS1, y = NMDS2, colour = treatment), linetype = 2) +
  ggtitle("NMDS 16s by sample type") +
  theme_classic()+
  facet_wrap(~species);p
ggsave(filename = "Figures/nmds_16s_all.pdf", plot = p, width = 12, height = 6, units = "in")

```

#amur only - differences between species data.Bac.seq.rel
```{r}
Bac.seq.S.rel.amur<-subset_samples(data.Bac.seq.rel, species=="Acropora muricata")
Bac.seq.S.rel.amur = prune_taxa(taxa_sums(Bac.seq.S.rel.amur) > 0, Bac.seq.S.rel.amur) 
#make unifrac matrix
Bac.seq.wu.ini <- phyloseq::distance(Bac.seq.S.rel.amur, method = "wunifrac")
s.u.samp.df.ini <- as(sample_data(Bac.seq.S.rel.amur), "data.frame") #sample df
s.u.samp.df.ini$treatment<-as.factor(s.u.samp.df.ini$treatment)
  
#adonixs test between sample types: p=0.001 between sample types
set.seed(30)
adonis_results<-adonis2(Bac.seq.wu.ini ~ treatment, data = s.u.samp.df.ini)
# Pairwise comparisons using pairwise.adonis2
pairwise_results <- pairwise.adonis2(Bac.seq.wu.ini ~ treatment, data = s.u.samp.df.ini)
print(pairwise_results)

# Homogeneity of dispersion test  - no diffs
set.seed(30)
betadisper_result <- betadisper(Bac.seq.wu.ini, s.u.samp.df.ini$treatment, type = "centroid")
permutest_result <- permutest(betadisper_result)

# Tukey's Honest Significant Difference test
tukey_result <- TukeyHSD(betadisper_result, ordered = FALSE, conf.level = 0.95)

#plot
#nmds
unifrac.ini <- ordinate(Bac.seq.S.rel.amur, method="NMDS", "unifrac",weighted=TRUE, set.seed(30)) 
stressplot(unifrac.ini)
print(unifrac.ini)# stress score 6.857006e-05 
scores.ord.u_RelA_stats<-as.data.frame(cbind(vegan::scores(unifrac.ini, display="sites")))  
     unifrac.ini.sd <- as(sample_data(Bac.seq.S.rel.amur), "data.frame") #sample df

scores.ord.u_RelA_stats$treatment <- unifrac.ini.sd$treatment

p<-ggplot(scores.ord.u_RelA_stats, aes(x = NMDS1, y = NMDS2)) + 
  geom_point(aes(colour = treatment), size = 4) +
    scale_color_manual(values=c("orange","turquoise3","seagreen"))+
  stat_ellipse(aes(x = NMDS1, y = NMDS2, colour = treatment), linetype = 2) +
  ggtitle("Microbiome NMDS") +
  theme_classic();p
ggsave("Figures/amur_NMDS.pdf", plot = p, width = 8, height = 6)


# Access the OTU table from your phyloseq object
otu_table <- otu_table(Bac.seq.S.rel.amur)

# Count the number of non-zero counts for each taxa across all samples
taxa_presence <- rowSums(otu_table > 0) 
num_taxa_present_in_all_samples <- sum(taxa_presence == ncol(otu_table))# Count the number of taxa present in all samples
print(num_taxa_present_in_all_samples)# Print the result - it's zero

# Calculate prevalence of taxa
taxa_prevalence <- prevalence(Bac.seq.S.rel.amur, detection = 1/100)
tax_table <- tax_table(Bac.seq.S.rel.amur)

# Filter taxa with prevalence greater than 1%
taxa_greater_than_80_percent <- taxa_prevalence[taxa_prevalence > 0.80]
taxa_names_greater_than_80_percent <- tax_table[taxa_greater_than_80_percent,]

# Count the number of taxa
num_taxa_greater_than_80_percent <- length(taxa_names_greater_than_80_percent)

# Print the result
print(length(taxa_greater_than_80_percent))
print(taxa_names_greater_than_80_percent)


# Count unique taxa
taxa_levels <- as.data.frame(tax_table(Bac.seq.S.rel.amur))
unique_species <- n_distinct(taxa_levels$Species)
unique_genera <- n_distinct(taxa_levels$Genus)
unique_families <- n_distinct(taxa_levels$Family)

print(unique_species)
print(unique_genera)
print(unique_families)

# Count unique OTUs or ASVs (this is too high res)
otu_table <- otu_table(Bac.seq.S.rel.amur)
unique_otus <- sum(otu_table > 0, na.rm = TRUE)
print(unique_otus)

core.taxa.standard <- core_members(Bac.seq.S.rel.amur, detection = 0.0001, prevalence = .95)
core.taxa.standard

#Try again with genus level
cnat.rel.gen <- aggregate_taxa(Bac.seq.S.rel.amur, "Family")
prevalences <- seq(.05, 1, .05)
detections <- round(10^seq(log10(1e-5), log10(.2), length = 10), 3)
par(cex = 0.2)  # Adjust the value (0.8) to make the text smaller

p1 <- plot_core(cnat.rel.gen, 
                plot.type = "heatmap", 
                colours = rev(brewer.pal(5, "RdBu")),
                prevalences = prevalences,
                
                detections = detections, min.prevalence = .95) +
    xlab("Detection Threshold (Relative Abundance (%))")
p1 <- p1 + theme_bw() + ylab("ASVs")
p1

amur.genus <- aggregate_taxa(Bac.seq.S.rel.amur, "Genus")
prevalences <- seq(.05, 1, .05)
detections <- round(10^seq(log10(1e-5), log10(.2), length = 10), 3)

p1 <- plot_core(amur.genus, 
                plot.type = "heatmap", 
                colours = rev(brewer.pal(5, "RdBu")),
                prevalences = prevalences, 
                detections = detections, min.prevalence = .5) +
    xlab("Detection Threshold (Relative Abundance (%))")
p1 <- p1 + theme_bw() + ylab("ASVs")
p1

#bar plot
#family
Bac.fam.amur <- Bac.seq.S.rel.amur %>% 
  tax_glom(taxrank = "Family", NArm = FALSE) %>% 
  transform_sample_counts(function(x) {x/sum(x)} ) 
  Bac.fam.melt.amur <- psmelt(Bac.fam.amur)
Bac.fam.melt.amur$treatment_sample <- paste(Bac.fam.melt.amur$treatment, Bac.fam.melt.amur$sample_name, sep = "_")


  ggplot(Bac.fam.melt.amur, aes(x = treatment_sample, y = Abundance, fill = Family)) +
  geom_bar(stat = "identity") +
  #scale_fill_manual(values=pal) +
  #scale_color_manual(values=pal$hex)+
  #scale_fill_manual(values = palette) +  # Use scale_fill_manual() for filling bars
  ylab("Relative Abundance") +
  xlab("individual") +
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(angle = 90, hjust = 1))+  
    ggtitle("C. natans Family")   # Add plot title here
  
  
  ggplot(Bac.fam.melt.amur, aes(x = treatment, y = Abundance, fill = Family)) +
  geom_bar(stat = "identity") +
  #scale_fill_manual(values=pal) +
  #scale_color_manual(values=pal$hex)+
  #scale_fill_manual(values = palette) +  # Use scale_fill_manual() for filling bars
  ylab("Relative Abundance") +
  xlab("individual") +
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(angle = 90, hjust = 1))+  
    ggtitle("C. natans Family")   # Add plot title here
  
  #bar plot
#phy
Bac.phy.amur <- Bac.seq.S.rel.amur %>% 
  tax_glom(taxrank = "Phylum", NArm = FALSE) %>% 
  transform_sample_counts(function(x) {x/sum(x)} ) 
  Bac.phy.melt.amur <- psmelt(Bac.phy.amur)
Bac.phy.melt.amur$treatment_sample <- paste(Bac.phy.melt.amur$treatment, Bac.phy.melt.amur$sample_name, sep = "_")

  ggplot(Bac.phy.melt.amur, aes(x = treatment_sample, y = Abundance, fill = Phylum)) +
  geom_bar(stat = "identity") +
  #scale_fill_manual(values=pal) +
  #scale_color_manual(values=pal$hex)+
  #scale_fill_manual(values = palette) +  # Use scale_fill_manual() for filling bars
  ylab("Relative Abundance") +
  xlab("individual") +
  #theme(legend.position = "none")+
  theme(axis.text.x = element_text(angle = 90, hjust = 1))+  
    ggtitle("C. natans Phylum")   # Add plot title here
  
  
  ### HE from ACE
  
  ##Core Analysis
  amur.core <- core(Bac.seq.S.rel.amur, detection = 0.0001, prevalence = .99)
amur.core.taxa <- tax_table(amur.core)
View(as.data.frame(amur.core.taxa))


#Trial with a tax glom at family??
t0.fam <- tax_glom(Bac.seq.S.rel.amur, "Family", NArm = TRUE)
t0.fam.core <- core(t0.fam, detection = 0.0001, prevalence = .99)
t0.fam.core.taxa <- tax_table(t0.fam.core)
View(as.data.frame(t0.fam.core.taxa))

#amur
#amur <- subset_samples(Bac.seq.S.rel2, species == "Colpophyllia natans")
#amur.ra <- transform_sample_counts(amur, function(x) x/ sum(x))

amur.core <- core(Bac.seq.S.rel.amur, detection = 0.0001, prevalence = .97)
amur.core.taxa <- tax_table(amur.core)
View(as.data.frame(amur.core.taxa))
amur.core.melt <- psmelt(amur.core)
amur.core.melt$top.group <- "core"
write.csv(amur.core.melt, "stats/amur_core.csv")
amur.core.melt$treatment_sample<-paste(amur.core.melt$treatment, amur.core.melt$sample_name, sep = "_")
##Plotting
#check # of OTUs
p.amur <- ggplot(amur.core.melt, aes(x = treatment_sample, y = Genus, size = Abundance, color=treatment)) +
  geom_point() +
  scale_size_area(max_size = 6, breaks = c(0.05, 0.1, 0.3, 0.5, 0.7, 0.9 )) +
  coord_fixed(ratio = 0.9) +
  scale_color_manual(values=c("dodgerblue4", "darkorange2","indianred3")) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1));p.amur
print(p.amur)
ggsave("Figures/amur_core_bubble.pdf")

```

venn
```{r}
##Can we draw a venn diagram?
library(tidyverse)
amur.core.melt.0<-subset(amur.core.melt, treatment=="0")
amur.core.melt.0 <- amur.core.melt.0 %>% unite(OTU, Genus, col='otu_genus',sep='-')
amur.core.melt.0.list <- unique(amur.core.melt.0$otu_genus)

amur.core.melt.1<-subset(amur.core.melt, treatment=="1")
amur.core.melt.1 <- amur.core.melt.1 %>% unite(OTU, Genus, col='otu_genus',sep='-')
amur.core.melt.1.list <- unique(amur.core.melt.1$otu_genus)

amur.core.melt.5.3<-subset(amur.core.melt, treatment=="5.3")
amur.core.melt.5.3 <- amur.core.melt.5.3 %>% unite(OTU, Genus, col='otu_genus',sep='-')
amur.core.melt.5.3.list <- unique(amur.core.melt.5.3$otu_genus)

candidates <- list("1"=amur.core.melt.1.list,"0"=amur.core.melt.0.list,"5.3"=amur.core.melt.5.3.list)
library(VennDiagram)
venn <- venn.diagram(x = candidates, filename = NULL, fill = c("#E69F00", "#56B4E9", "#CC79A7"), alpha = 0.5)
pdf(file = "../output/venn_core_T0.pdf")
grid.draw(venn)
dev.off()
overlap <- calculate.overlap(candidates)
names(overlap) <- c("mcap pcomp pvar pacu", "mcap pcomp pvar", "mcap pcomp pacu", "mcap pvar pacu", "pcomp pvar pacu", "mcap pcomp", "mcap pvar ", 
                    "mcap pacu", "pcomp pvar", "pcomp  pacu", "pvar pacu", "mcap", "pcomp", "pvar", "pacu")
View(overlap)
```










alpha
Bac.seqFLU.15k
```{r}

Bac.seq.raw.amur<-subset_samples(Bac.seqFLU.15k, species=="Acropora muricata")
Bac.seq.raw.amur = prune_taxa(taxa_sums(Bac.seq.raw.amur) > 0, Bac.seq.raw.amur) 
#make unifrac matrix
Bac.seq.wu.ini <- phyloseq::distance(Bac.seq.raw.amur, method = "wunifrac")
s.u.samp.df.ini <- as(sample_data(Bac.seq.raw.amur), "data.frame") #sample df
s.u.samp.df.ini$treatment<-as.factor(s.u.samp.df.ini$treatment)
  
# pull out: observed, diversity_shannon, evenness_pielou
erich.tab.obs <-microbiome::alpha(Bac.seqFLU.15k, index = "observed") 
  erich.tab.obs$sample_name <- as.factor(Bac.seqFLU.15k.sd$sample_name)
    erich.tab.obs$treatment <- as.factor(Bac.seqFLU.15k.sd$treatment)

erich.tab.shan <-microbiome::alpha(Bac.seqFLU.15k, index = "diversity_shannon")
    erich.tab.shan$sample_name <- as.factor(Bac.seqFLU.15k.sd$sample_name)
        erich.tab.shan$treatment <- as.factor(Bac.seqFLU.15k.sd$treatment)

erich.tab.even <-microbiome::alpha(Bac.seqFLU.15k, index = "evenness_pielou")
    erich.tab.even$sample_name <- as.factor(Bac.seqFLU.15k.sd$sample_name)
        erich.tab.shan$treatment <- as.factor(Bac.seqFLU.15k.sd$treatment)


alpha<-merge(erich.tab.obs, erich.tab.even, by.all="sample_name")
alpha<-merge(alpha, erich.tab.shan, by="sample_name")
#write.csv(erich.tab.obs, "erich.tab.obs.csv")
#add meta
alpha<-merge(alpha, Bac.seqFLU.15k.sd, by.x="sample_name")
```

Shannon Diversity
```{r}
#shannon ####
  hist(alpha$diversity_shannon)
  set.seed(30)
  aov.shannon = aov(diversity_shannon ~ treatment, data=alpha)
    summary(aov.shannon) # home p=0.0285, genet p=0.0002, home*away p=0.039
    
#means
shannon_mean <- ddply(alpha, c("treatment"), summarise, #summarize cell counts
                 N    = length(diversity_shannon[!is.na(diversity_shannon)]), #calculate the length of the data frame, excluding NA’s
                 mean = mean(diversity_shannon, na.rm=TRUE), #calculate mean of response variable, removing NA's
                 sd   = sd(diversity_shannon, na.rm=TRUE), #calculate standard deviation
                 se   = sd / sqrt(N), #calculate standard error
                 max = max(diversity_shannon, na.rm=TRUE) #calculate max, could also calculate min () if desired
);shannon_mean

shannon_plot<-ggplot(data=shannon_mean, aes(x=treatment, y=mean, color=treatment)) +
  geom_errorbar(aes(ymin=mean-se, ymax=mean+se),
                width=0.1, show.legend = T)+
  geom_point(aes(color=treatment), size=4, show.legend = F)+
  xlab("") + #Label the X Axis
    ylab("") + #Label the X Axis
  theme_bw() + #Set the background color
  theme(axis.line = element_line(color = 'black'), #Set the axes color
        axis.title=element_text(size=14,face="bold"), #Set axis format
        panel.border = element_blank(), #Set the border
        panel.grid.major = element_blank(), #Set the major gridlines
        panel.grid.minor = element_blank(), #Set the minor gridlines
        text = element_text(size=18),  # set element text
        plot.background =element_blank(), #Set the plot background
        legend.key = element_blank()) + #Set plot legend key
  # theme(panel.grid.major = element_blank(), 
  #       panel.grid.minor = element_blank(),
  #       panel.background = element_rect(colour = "black", size=1))+
        theme(aspect.ratio=1)+
   ylab(expression(paste("Shannon Diversity"))) +
   ggtitle("Shannon by treatmetn")+
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  theme(plot.title = element_text(size=20, face = "italic"));shannon_plot



```
Observed Richness
```{r}
#Richness ####
  hist(alpha$observed)
  set.seed(30)
  aov.observed = aov(observed ~ treatment, data=alpha)
    summary(aov.observed) # away p=0.038
    
#means
observed_mean <- ddply(alpha, c("treatment"), summarise, #summarize cell counts
                 N    = length(observed[!is.na(observed)]), #calculate the length of the data frame, excluding NA’s
                 mean = mean(observed, na.rm=TRUE), #calculate mean of response variable, removing NA's
                 sd   = sd(observed, na.rm=TRUE), #calculate standard deviation
                 se   = sd / sqrt(N), #calculate standard error
                 max = max(observed, na.rm=TRUE) #calculate max, could also calculate min () if desired
);observed_mean

observed_plot<-ggplot(data=observed_mean, aes(x=treatment, y=mean, color=treatment)) +
  geom_errorbar(aes(ymin=mean-se, ymax=mean+se),
                width=0.1, show.legend = T)+
  geom_point(aes(color=treatment), size=4, show.legend = F)+
  xlab("Away Nursery") + #Label the X Axis
    ylab("Observed") + #Label the X Axis
  theme_bw() + #Set the background color
  theme(axis.line = element_line(color = 'black'), #Set the axes color
        axis.title=element_text(size=14,face="bold"), #Set axis format
        panel.border = element_blank(), #Set the border
        panel.grid.major = element_blank(), #Set the major gridlines
        panel.grid.minor = element_blank(), #Set the minor gridlines
        text = element_text(size=18),  # set element text
        plot.background =element_blank(), #Set the plot background
        legend.key = element_blank()) + #Set plot legend key
  # theme(panel.grid.major = element_blank(), 
  #       panel.grid.minor = element_blank(),
  #       panel.background = element_rect(colour = "black", size=1))+
        theme(aspect.ratio=1)+
   ylab(expression(paste("observed Diversity"))) +
   ggtitle("observed by treatment")+
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  theme(plot.title = element_text(size=20, face = "italic"));observed_plot


```
Evenness
```{r}
#evenness ####
  hist(alpha$evenness_pielou)
  set.seed(30)
  aov.evenness = aov(evenness_pielou ~ treatment, data=alpha)
    summary(aov.evenness) # home p<0.001, away p<0.001, genet p<0.001, home*away p<0.001
    
#means
evenness_mean <- ddply(alpha, c("treatment"), summarise, #summarize cell counts
                 N    = length(evenness_pielou[!is.na(evenness_pielou)]), #calculate the length of the data frame, excluding NA’s
                 mean = mean(evenness_pielou, na.rm=TRUE), #calculate mean of response variable, removing NA's
                 sd   = sd(evenness_pielou, na.rm=TRUE), #calculate standard deviation
                 se   = sd / sqrt(N), #calculate standard error
                 max = max(evenness_pielou, na.rm=TRUE) #calculate max, could also calculate min () if desired
);evenness_mean

evenness_plot<-ggplot(data=evenness_mean, aes(x=treatment, y=mean, color=treatment)) +
  geom_errorbar(aes(ymin=mean-se, ymax=mean+se),
                width=0.1, show.legend = T)+
  geom_point(aes(color=treatment), size=4, show.legend = F)+
  xlab("Home") + #Label the X Axis
    ylab("") + #Label the X Axis
  theme_bw() + #Set the background color
  theme(axis.line = element_line(color = 'black'), #Set the axes color
        axis.title=element_text(size=14,face="bold"), #Set axis format
        panel.border = element_blank(), #Set the border
        panel.grid.major = element_blank(), #Set the major gridlines
        panel.grid.minor = element_blank(), #Set the minor gridlines
        text = element_text(size=18),  # set element text
        plot.background =element_blank(), #Set the plot background
        legend.key = element_blank()) + #Set plot legend key
  # theme(panel.grid.major = element_blank(), 
  #       panel.grid.minor = element_blank(),
  #       panel.background = element_rect(colour = "black", size=1))+
        theme(aspect.ratio=1)+
   ylab(expression(paste("evenness Diversity"))) +
   ggtitle("evenness by treatment")+
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  theme(plot.title = element_text(size=20, face = "italic"));evenness_plot




```

try these

```{r}
#regular box  
#evenness
  aov.evenness.species = aov(evenness_pielou ~ treat, data=alpha)
  summary(aov.evenness.species) # sig diff between species
  TukeyHSD(aov.evenness.species)  

  #Plot
  boxplot(diversity_shannon ~ treatment, data=alpha, ylab="shannon diversity") 
  boxplot(observed ~ treatment, data=alpha, ylab="Observed") 
  boxplot(evenness_pielou ~ treatment, data=alpha, ylab="Evenness_pielou") 

#violin plots
  # create a list of pairwise comaprisons
al.species <- levels(alpha$treatment) # get the variables



#observed
p1 <- ggviolin(alpha, x = "treatment", y = "diversity_shannon",
   add = "boxplot", fill = "treatment") 
  print(p1)

    p1 <- ggviolin(alpha, x = "tag.id", y = "diversity_shannon",
   add = "boxplot", fill = "treatment") 
  print(p1)

  #observed
p1 <- ggviolin(alpha, x = "treatment", y = "observed",
   add = "boxplot", fill = "treatment") 
  print(p1)
  
p1 <- p1 + stat_compare_means(comparisons = "tag.id") #non-parametric test (Wilcoxon test)
  print(p1)
  
p1 <- ggviolin(alpha, x = "tag.id", y = "diversity_observed",
   add = "boxplot", fill = "treatment") 
  print(p1)
  
#Evenness
p1 <- ggviolin(alpha, x = "treatment", y = "evenness_pielou",
   add = "boxplot", fill = "treatment") 
  print(p1)
  
  
p1 <- p1 + stat_compare_means(comparisons = "treatment") #non-parametric test (Wilcoxon test)
  print(p1)

```

